#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/shirodemo?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root

#mybatis
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.shiro.shiroDemo.model
